# Generated by Django 3.0.8 on 2021-11-24 05:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuselectbyuser',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
